project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "abc.qmd"

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: abc.qmd
        text: abc

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
filters:
  - webr
