project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
      - href: abc.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
filters:
  - webr


